import * as fs from "node:fs"
import * as path from "node:path"
import { RidgelineConfig } from "../types"

const PLUGIN_JSON_MARKER = "ridgeline-auto-generated"

const pluginJson = (name: string): string =>
  JSON.stringify({ name, description: PLUGIN_JSON_MARKER }, null, 2) + "\n"

const isPluginDir = (dir: string): boolean => {
  const pluginDir = path.join(dir, "plugin")
  if (!fs.existsSync(pluginDir) || !fs.statSync(pluginDir).isDirectory()) return false
  return fs.readdirSync(pluginDir).length > 0
}

const ensurePluginJson = (dir: string, name: string): boolean => {
  const pluginJsonPath = path.join(dir, "plugin.json")
  if (fs.existsSync(pluginJsonPath)) return false
  fs.writeFileSync(pluginJsonPath, pluginJson(name))
  return true
}

const isAutoGenerated = (dir: string): boolean => {
  const pluginJsonPath = path.join(dir, "plugin.json")
  try {
    const content = JSON.parse(fs.readFileSync(pluginJsonPath, "utf-8"))
    return content.description === PLUGIN_JSON_MARKER
  } catch {
    return false
  }
}

export type PluginDir = {
  dir: string
  createdPluginJson: boolean
}

export const discoverPluginDirs = (config: RidgelineConfig): PluginDir[] => {
  const dirs: PluginDir[] = []

  const candidates = [
    { base: config.buildDir, name: `ridgeline-build-${config.buildName}` },
    { base: config.ridgelineDir, name: "ridgeline-project" },
  ]

  for (const { base, name } of candidates) {
    if (!isPluginDir(base)) continue
    const pluginDir = path.join(base, "plugin")
    const createdPluginJson = ensurePluginJson(pluginDir, name)
    dirs.push({ dir: pluginDir, createdPluginJson })
  }

  return dirs
}

export const cleanupPluginDirs = (dirs: PluginDir[]): void => {
  for (const { dir, createdPluginJson } of dirs) {
    if (!createdPluginJson) continue
    if (!isAutoGenerated(dir)) continue
    try {
      fs.unlinkSync(path.join(dir, "plugin.json"))
    } catch {
      // Best-effort cleanup
    }
  }
}
