import * as fs from "node:fs"
import * as path from "node:path"
import { RidgelineConfig } from "../types"

const PLUGIN_JSON_MARKER = "ridgeline-auto-generated"

const pluginJson = (name: string): string =>
  JSON.stringify({ name, description: PLUGIN_JSON_MARKER }, null, 2) + "\n"

const hasSkills = (dir: string): boolean => {
  const skillsDir = path.join(dir, "skills")
  if (!fs.existsSync(skillsDir) || !fs.statSync(skillsDir).isDirectory()) return false
  return fs.readdirSync(skillsDir).length > 0
}

const ensurePluginJson = (dir: string, name: string): boolean => {
  const pluginJsonPath = path.join(dir, "plugin.json")
  if (fs.existsSync(pluginJsonPath)) return false
  fs.writeFileSync(pluginJsonPath, pluginJson(name))
  return true
}

const isAutoGenerated = (dir: string): boolean => {
  const pluginJsonPath = path.join(dir, "plugin.json")
  try {
    const content = JSON.parse(fs.readFileSync(pluginJsonPath, "utf-8"))
    return content.description === PLUGIN_JSON_MARKER
  } catch {
    return false
  }
}

export type SkillPluginDir = {
  dir: string
  createdPluginJson: boolean
}

export const discoverSkillDirs = (config: RidgelineConfig): SkillPluginDir[] => {
  const dirs: SkillPluginDir[] = []

  const candidates = [
    { dir: config.buildDir, name: `ridgeline-build-${config.buildName}` },
    { dir: config.ridgelineDir, name: "ridgeline-project" },
  ]

  for (const { dir, name } of candidates) {
    if (!hasSkills(dir)) continue
    const createdPluginJson = ensurePluginJson(dir, name)
    dirs.push({ dir, createdPluginJson })
  }

  return dirs
}

export const cleanupSkillDirs = (dirs: SkillPluginDir[]): void => {
  for (const { dir, createdPluginJson } of dirs) {
    if (!createdPluginJson) continue
    if (!isAutoGenerated(dir)) continue
    try {
      fs.unlinkSync(path.join(dir, "plugin.json"))
    } catch {
      // Best-effort cleanup
    }
  }
}
